# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e1a32f350ca5801b71c3fb2278c2f1f2e970c589425bffc4f69095f14a34734bd036147446691419255bf4b340e6d35f783498006cd194f60a9ab8fe73ca35c

test:
  secret_key_base: 8185a21ad373e34ebf09d3243ca477573a18cfdf4203f725f6e31729327e0492e50d46b6220268dfe1cc6263e0d897a9b3f04bf6bd81dce738bdc35b59006a6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
